name: PR_open_workflow

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  PR_open_workflow:
    name: PR_open_workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.5
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Result
      run: |
        echo "PR opened. Hence, this msg"
